server:
  port: 8000
  servlet:
    context-path: /exchange-service/api/v1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: exchange-service
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: exchange
    password: exchange
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      import-check:
        enabled: false