server:
  port: 8100
  servlet:
    context-path: /book-service/api/v1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/book
    username: book
    password: book
  cloud:
    config:
      import-check:
        enabled: false
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect