server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RaphaSalomao/config-server-remote.git
          default-label: main
          search-paths:
            - 'greeting-service*'